### ISSUE TITLE
Functioneel toepassingsgebied van de standaard benoemen

### ISSUE THREAD

**Issue by adgerrits** [Logius-standaarden/NL-GOV-profile-for-CloudEvents#12]
In het profiel staat nu: "_CloudEvents is a vendor neutral specification for defining the format of event data. This specification profiles the CloudEvents specification to standardize the automated exchange of information about events, specifically applicable to the Dutch government._" Mede n.a.v. een gesprek hierover in het Technisch Overleg is het wenselijk om helder te definiëren wat het functioneel toepassingsgebied is. 

Mijn voorkeur gaat uit naar een zo breed mogelijk bereik omdat gebruik van het profiel meerwaarde kan hebben in (vrijwel) _alle situaties_ waarin gebeurtenisgegevens worden uitgewisseld. Waarbij het kan gaan om basisgegevens, andersoortige brongegevens of niet-brongegevens. 

In termen van het Forum Standaardisatie:
**Functioneel toepassingsgebied**:  Het NL GOV CloudEvents Profile moet worden toegepast op de uitwisseling van gegevens over plaatsgevonden gebeurtenissen.
**Organisatorisch werkingsgebied**: Nederlandse overheden (Rijk, provincies, gemeenten en Waterschappen) en instellingen uit de (semi-) publieke sector.
**Domein**: Uitwisselilngsfundament

**Comment by edwinwisse** [comment]
Door het functioneel toepassingsgebied heel breed te maken ("gegevens over plaatsgevonden gebeurtenissen") lopen we mogelijk tegen weerstand in het opnemen op de PTOLU lijst van het Forum. We kunnen wel streven naar breder toepassing voor alle gebeurtenissen en het toepassingsgebied kan dan later nog breder gemaakt worden. 
Ik heb de vraag naar het toepassingsgebied wel doorgespeeld naar het Bureau Forum Standaardisatie.

**Comment by adgerrits** [comment]
Dat mag in het TO worden toegelicht. Juist van het Forum verwacht ik dat ze streven naar zo breed mogelijk gebruikte standaarden.

**Comment by edwinwisse** [comment]
In de aanvraag bij het Forum Standaardisatie is nu de volgende tekst opgenomen voor de toepassingsgebieden:

> Wat is het beoogde functioneel toepassingsgebied voor de standaard?
> - Het uitwisselen van notificaties op wijzigingen in de basisregistraties en andere registraties binnen het Federatief Datastelsel.   

en

> Wat is het beoogde organisatorisch werkingsgebied voor de standaard?
> - Het Federatief Data Stelsel (FDS). In het FDS is het NLGOV CloudEvents profiel al opgenomen als een verplichte standaard.

en in het kader van de scope van de pas-toe-of-leg-uit lijst:

> Is het beoogde functioneel toepassingsgebied en het organisatorisch werkingsgebied van de standaard, voldoende breed om substantieel bij te dragen aan de interoperabiliteit van de (semi-)overheid?
> - Ja, de standaard is bedoeld om breed gebruikt te worden voor registraties in kader van het Federatief Data Stelsel (FDS). Allereerst kan de standaard toegepast worden voor de basisregistraties zoals de basisregistratie personen.
