### ISSUE TITLE
Update Github issue templates m.b.t. Digikoppeling

### ISSUE THREAD

**Issue by bwbroersma** [Logius-standaarden/NL-GOV-profile-for-CloudEvents#13]
Volgens mij moet hier geen Digikoppeling meer staan toch?

https://github.com/Logius-standaarden/NL-GOV-profile-for-CloudEvents/blob/589c86f5cb682ff121e5547bca31eb344b21afdc/.github/ISSUE_TEMPLATE/aanpassing_documentatie.yml#L2-L4

https://github.com/Logius-standaarden/NL-GOV-profile-for-CloudEvents/blob/589c86f5cb682ff121e5547bca31eb344b21afdc/.github/ISSUE_TEMPLATE/wijzigingsformulier.yml#L2-L4

**Comment by edwinwisse** [comment]
Gedaan, dank voor de correctie.
