### ISSUE TITLE
Gebruik voorbeeld Burgerservicenummers (BSNs)

### ISSUE THREAD

**Issue by bwbroersma** [Logius-standaarden/NL-GOV-profile-for-CloudEvents#14]
123456789 wordt gebruikt als voorbeeld Burgerservicenummer (BSN):
https://github.com/Logius-standaarden/NL-GOV-profile-for-CloudEvents/blob/a3b01187bfb451dd0c9ceae9a7d0a360a1895287/Context%20Attributes.md#L356

https://github.com/Logius-standaarden/NL-GOV-profile-for-CloudEvents/blob/a3b01187bfb451dd0c9ceae9a7d0a360a1895287/Example.md#L32-L42

N.b. is 1234567**7**89 een typo of expres?

Er zijn ook 'geldige' test nummers, zie ook https://www.rvig.nl/testbestanden-bvbsn (en https://www.rvig.nl/sites/default/files/2023-05/Test%20burgerservicenummers%20en%20A-nummers%20inclusief%20omnummertabel.ods).

**Comment by adgerrits** [comment]
Het was ooit expres om duidelijk te maken dat het een fictief nummer is. 
Dat het de elfproef niet doorstaat maakt dat helemaal duidelijk ;)
Maar een nummer uit de testset is wat mij betreft ook prima.
