### ISSUE TITLE
Als gebruiker van de standaard wil ik een neutrale beschrijving zodat ik zelf kan bepalen met welk doel ik de standaard toepas 

### ISSUE THREAD

**Issue by adgerrits** [Logius-standaarden/NL-GOV-profile-for-CloudEvents#3]
In de beschrijving van de standaard op https://www.logius.nl/diensten/nl-gov-profile-cloudevents wordt terecht gesteld dat de standaard het mogelijk maakt dat 'computersystemen elkaar kunnen notificeren over gebeurtenissen'. 
Maar vervolgens wordt gesteld dat het nut van de standaard (ook) is dat het niet langer nodig is om een kopie van gegevens te maken waardoor de kans op kopiefouten verdwijnt en de gebruikte opslagruimte afneemt. Dat is:

-  zeker niet altijd waar; er zijn genoeg situaties waarin je nog steeds lokaal gegevens nodig hebt.
- misplaatst bij de beschrijving van een standaard omdat je suggereert dat het ene doel van gebruik beter is dan het andere.

Binnen de CloudEvents-community wordt juist benadrukt dat de standaard neutraal van karakter is en dat zowel aanbieders als afnemers volledig zelf bepalen met welke doelen ze de standaard toepassen. 
Door in de beschrijving zo'n doel te benoemen ga je op de stoel van beleidsmakers of architecten zitten en stuur je, in mijn ogen ongewenst, op toepassing van de standaard. 

Ik stel voor de teksten in die richting te verwijderen.

**Comment by adgerrits** [comment]
Is het hier nog 1-weg of al 2-wegverkeer?

**Comment by edwinwisse** [comment]
Op dit moment wordt NL-CloudEvents nog niet actief beheerd. Er is nog geen technische werkgroep waarin wijzigingen behandeld kunnen worden en de standaard wordt ook nog niet geagendeerd in de tactische en strategische overleggen van standaarden. 
Vooralsnog is het beheer hier niet actief. Dat wil zeggen dat we de documentatie aanbieden en kleine, niet-inhoudelijke wijzigingen doorvoeren. Maar alle wijzigingsvoorstellen waarover discussie gevoerd moeten worden blijven dus even wachten tot actief beheer is ingericht.

**Comment by adgerrits** [comment]
Gelet op https://www.logius.nl/actueel/logius-neemt-standaard-nl-gov-profile-cloudevents-beheer wordt de standaard nu beheerd en kan de tekst worden aangepast toch?  
Verder nog een kleine typo op https://github.com/Logius-standaarden/NL-GOV-profile-for-CloudEvents/blob/develop/CONTRIBUTING.md staat onderaan de link https://github.com/Logius-standaarden/notificatieservices maar daarin is 'VNR-Realisatie' iets te enthousiast vervangen door 'Logius-standaarden'. De repo 
'https://github.com/VNG-Realisatie/notificatieservices' met info over het uitgevoerde project blijft bestaan (krijgt vandaag of morgen de status 'Gearchiveerd').

**Comment by adgerrits** [comment]
Er is ondertussen een technische werkgroep dus kan het issue opgepakt worden. Ik denk dat het belangrijk is om vanaf het begin heel duidelijk te zijn over wat wel en niet het doel van de standaard is. Er bestaat binnen de overheid momenteel veel ruis over het wat en waarom van 'data bij de bron' waarbij mensen allerlei doelen formuleren die m.i. niet wenselijk zijn. Ik zou die dus zeker niet willen verbinden aan nut en noodzaak van deze standaard. Eigenlijk vergelijkbaar met wat de CloudEvents-community doet door wat bewust buiten scope is geplaatst ook actief buiten scope te houden.

**Comment by edwinwisse** [comment]
We stellen door de volgende tekst op logius.nl:

> De snelheid van het uitwisselen is niet het enige voordeel van een standaard zoals NL GOV profile for CloudEvents. Door elkaar te notificeren kan informatie centraal of bij de bron bewaard worden. Het is dus niet langer nodig om een kopie van gegevens te maken. De kans op kopiefouten verdwijnt daarmee en ook de gebruikte opslagruimte neemt zo af. 

Te vervangen door de volgende tekst:

> De snelheid van het uitwisselen is niet het enige voordeel van een standaard zoals NL GOV profile for CloudEvents. Door elkaar te notificeren kan informatie centraal of bij de bron beheerd worden. Een kopie van een bronbestand kan actueel gehouden worden door notificaties vanuit een bronbestand te ontvangen en te verwerken.

**Comment by adgerrits** [comment]
Ik zou het nog korter houden: 
"NL GOV profile for CloudEvents is een set Nederlandse afspraken over het gebruik van de internationale standaard CloudEvents. De standaard beschrijft hoe gegevens over een plaatsgevonden gebeurtenis, zoals een verhuizing of overlijden, gestandaardiseerd kunnen worden uitgewisseld.   
Eventueel aangevuld met: "Organisaties kunnen daarmee beter samenwerken en informatie uitwisselen" Maar eigenlijk is dat een open deur omdat dit bij alle standaarden geldt. 
Dat afnemers notificaties kunnen gebruiken om een kopie actueel te houden is slechts een voorbeeld van wat ze met notificaties kunnen doen en hoeft er om die reden niet bij te staan. Er had bijv. ook kunnen staan: "Afnemers zijn zo snel op de hoogte van relevante veranderingen en kunnen daarop actie ondernemen".

**Comment by edwinwisse** [comment]
Goede laatste zin. De alinea wordt dan: 

> De snelheid van het uitwisselen is niet het enige voordeel van een standaard zoals NL GOV profile for CloudEvents. Door elkaar te notificeren kan informatie centraal of bij de bron beheerd worden. Afnemers zijn zo snel op de hoogte van relevante veranderingen en kunnen daarop actie ondernemen. 

Akkoord?

**Comment by adgerrits** [comment]
Tja... ik weet dat op dit moment binnen de overheid 'kopieën' (waarmee vaak vastleggingen worden bedoeld eat in mijn ogen trouwens geen kopieën zijn) als not done worden gezien. Ik kijk daar anders naar. Min of meer in lijn met de CloudEvents community die zich bewust verre houdt van allerlei zaken die een relatie met overdracht van gebeurtenisdata hebben (zowel technisch als inhoudelijk). Dus als de meeste mensen vinden dat het er bij moet staan, dan moet het er bij staan....

**Comment by edwinwisse** [comment]
Intussen heeft communicatie de website aangepast met mjin oorspronkelijke voorstel: [wat is CloudEvents?](https://www.logius.nl/domeinen/gegevensuitwisseling/nl-gov-profile-cloudevents/wat-nl-gov-profile-cloudevents). Kunnen we dit verzoek hiermee afsluiten?
