### ISSUE TITLE
#appendix-1-use-of-json-http-and-webhook 

### ISSUE THREAD

**Issue by mdriesse** [Logius-standaarden/NL-GOV-profile-for-CloudEvents#6]
### Soort

- [ ] Tekstuele fout
- [X] Verbetersuggestie
- [ ] Onduidelijke tekst

### Omschrijving

Apendix 1 contains references to NL GOV Guidelines for CloudEvents JSON, CloudEvents HTTP, and CloudEvents Webhook. These references however refer to content which is published on [https://github.com/VNG-Realisatie/notificatieservices](https://github.com/VNG-Realisatie/notificatieservices). This is raises the question whether or not these guidelines are an integral part of the NL-GOV CloudEvents standard and maintained by Logius? Clarification would be appreciated.

### Naam

M. Driessen

### Email

maurice.driessen@capgemini.com

### Organisatie

Capgemini

**Comment by edwinwisse** [comment]
Links have been corrected in the develop branch.
